# Generated by Django 2.0.1 on 2018-11-13 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'likes',
            },
        ),
        migrations.CreateModel(
            name='Want',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256)),
                ('status', models.IntegerField()),
                ('target_date', models.DateTimeField(blank=True, null=True)),
                ('publish_set', models.BooleanField(default=True)),
                ('achieve_date', models.DateTimeField(blank=True, null=True)),
                ('achieve_text', models.TextField(blank=True, null=True)),
                ('achieve_url', models.URLField(blank=True, null=True)),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wants',
            },
        ),
        migrations.AddField(
            model_name='like',
            name='wantid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='wants.Want'),
        ),
    ]
