# Generated by Django 2.0.1 on 2018-11-13 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='status',
            field=models.CharField(choices=[('nostart', '未着手'), ('doing', '実施中'), ('done', '達成')], default='nostart', max_length=8),
        ),
    ]
