# Generated by Django 2.0.1 on 2018-11-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0002_auto_20181114_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='want',
            old_name='userid',
            new_name='user',
        ),
    ]
