# Generated by Django 2.0.1 on 2018-11-17 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0003_auto_20181116_1258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='like',
            old_name='p_userid',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='wantid',
            new_name='want',
        ),
    ]
