# Generated by Django 2.0.1 on 2018-11-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0004_auto_20181117_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='like_num',
            field=models.IntegerField(default=0),
        ),
    ]
