# Generated by Django 2.0.1 on 2018-11-24 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0005_want_like_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='create_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
