# Generated by Django 2.0.1 on 2018-11-24 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0006_want_create_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='want',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 11, 24, 23, 3, 0, 664436)),
        ),
    ]
