# Generated by Django 2.0.1 on 2019-01-08 04:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wants', '0007_auto_20181124_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='want',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='want',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 8, 13, 4, 40, 877670)),
        ),
    ]
