# Generated by Django 2.0.1 on 2018-11-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=128, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
                ('twitter_url', models.URLField()),
                ('intro_text', models.TextField()),
                ('image', models.ImageField(upload_to='media/')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user',
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
    ]
