# Generated by Django 2.0.1 on 2018-11-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='intro_text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='twitter_url',
            field=models.URLField(blank=True),
        ),
    ]
