# Generated by Django 2.0.1 on 2018-11-09 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20181109_2141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='twitter_url',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
